apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: medgenome-api-ingress
  namespace: medgenome
spec:
  podSelector:
    matchLabels:
      app: medgenome-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8000
